spring.application.name=order-management

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/public_db
spring.datasource.username=public_user
spring.datasource.password=publicN3xt!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://public_user:publicN3xt!@localhost:27017/order_events_db?authSource=admin
spring.data.mongodb.database=order_events_db

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
